/**
 * determinator-ls-example.ts
 *
 * Przykładowy skrypt dla agenta determinator.
 * Wykonuje "ls -la" w cwd, zapisuje wynik do output.
 *
 * Użycie:
 *   /run determinator '{"script": "'$(pwd)'/examples/determinator-ls-example.ts"}'
 */

import type { DeterminatorScript } from "../src/determinator/interface";

const script: DeterminatorScript = async (ctx) => {
  ctx.log("Starting determinator-ls-example...");

  // Wykonaj ls -la
  const { stdout, stderr } = await ctx.exec("ls -la");

  const readmeContent = ctx.inputs.length > 0
    ? await ctx.readFile(ctx.inputs[0]!).catch(() => "(file not found)")
    : "(no inputs)";

  // Zbuduj raport
  const content = [
    "# Deterministic LS Report\n",
    `Generated by determinator at ${new Date().toISOString()}\n`,
    "## Directory listing\n",
    "```",
    stdout,
    "```\n",
    "## Errors",
    stderr ? `\`\`\`\n${stderr}\n\`\`\`` : "(none)\n",
    "## Context\n",
    `- **cwd**: ${ctx.cwd}`,
    `- **inputs**: ${ctx.inputs.join(", ") || "(none)"}`,
    `- **output**: ${ctx.output}`,
    `- **chainDir**: ${ctx.chainDir}`,
    `- **runId**: ${ctx.runId}`,
    `- **params**: ${JSON.stringify(ctx.params)}`,
    "",
    "## First input preview",
    "```",
    readmeContent.slice(0, 500),
    "```",
  ].join("\n");

  await ctx.writeFile(ctx.output, content);
  ctx.log("Report written successfully");

  return { exitCode: 0, output: content };
};

export default script;
